### ISSUE TITLE
文字コードを JIS → UTF-8 に?

### ISSUE THREAD

**Issue by t-tk** [texjporg/pbibtex-base#2]
bibtexuの日本語(CJK)対応 https://github.com/texjporg/tex-jp-build/issues/139 に関連し
pbibtex-base の配布の文字コード(エンコーディング)を現状の JIS (ISO-2022-JP) から UTF-8 に変更したい、という案です。
テスト用に UTF-8 に変換したものをブランチ encoding-utf8 に入れてみます。

従来 pbibtex-base の配布は ISO-2022-JP でした。(u)pTeX と (u)pBibTeX を前提とした場合、ユーザー側がどの環境(Windows/Mac/Unix等)でどの文字コードを選んでも動くし、(u)pBibTeX の文字コードを UTF-8 で使っていれば、XeTeX, LuaTeX との組み合わせでも動くはずで、適切だったと思います。
で、今回、 bibtexu の日本語(CJK)対応を進めています。
bibtexuと一緒に使おうとすると、*.bst, *.bib が UTF-8 である必要があり bibtexu にとっては pbibtex-base が UTF-8 の方がありがたい状況です。
pbibtex-base を UTF-8 にした場合、upTeX, upBibTeX, XeTeX, LuaTeX では問題ありません。
Windows ではファイル毎の文字コードの自動判定が使えるので問題ないはずです。
Windows以外でも pTeX, pBibTeX を UTF-8 で使っている場合も問題ありません。
しかし、pTeX, pBibTeX を Mac, Linux 上でShift_JIS, EUCなどで使っている場合、文字コードの自動判定は含まれていないので動かなくなってしまいます。
UTF-8化を進めようとした場合、方針案は以下と思います。

[1] pTeX, pBibTeX を Mac, Linux 上で使う場合、文字コードを UTF-8 にしてもらうようお願いする。
[2] PTEXENC に Windows版(W32TeX版) のようなファイル毎の文字コード判定機能を追加する。

もう 2022年にもなって UTF-8 でないと動かないソフトもどんどん増えている状況なので [1] でもよいというのが私の考えです。
いかがでしょうか。

**Comment by aminophen** [comment]
UTF-8 化についてはいまいちどうするのが良いか，まだ迷っています。一番の懸念は

> Windows ではファイル毎の文字コードの自動判定が使えるので問題ないはずです。

に対して，まだ TeX Live 公式ソースに nkf ライブラリが組み込まれていない点です。まずはそれを入れられるのかどうか考えてからにしたいです（W32TeX はすでに提供終了，TeX Live win32 が今後どうなっていくのか…）。

また，現状の pbibtex-base のスタイル群は TEXMFDIST/pbibtex ディレクトリ以下にインストールされていて，texmf.cnf の「BSTINPUT 変数の (u)pbibtex 版」(BSTINPUT.pbibtex, BSTINPUT.upbibtex) でしか参照されないので，単に UTF-8 化するだけではうまくいかないと思います。BSTINPUT.bibtexu のような変数を用意して TEXMFDIST/pbibtex ディレクトリを参照させつつ，UTF-8 化するような流れでしょうか。

**Comment by t-tk** [comment]
> まだ TeX Live 公式ソースに nkf ライブラリが組み込まれていない点です。まずはそれを入れられるのかどうか考えてからにしたいです（W32TeX はすでに提供終了，TeX Live win32 が今後どうなっていくのか…）。

その点を踏まえて、nkfの文字コード判定部分の代替を書いてみました→ https://github.com/texjporg/tex-jp-build/issues/142

BSTINPUT.bibtexu はそうですね。標準のtexmf.cnfに入れる方向で考えたいです。

**Comment by t-tk** [comment]
BIBINPUTS.bibtexu, BSTINPUTS.bibtexu は pbibtex のところも読むように標準の texmf.cnfに入れました。
https://tug.org/svn/texlive?view=revision&revision=65917

pbibtex-base のファイルをUTF-8にしたものを CTAN に投稿しました。
mac, linuxで EUC-JP などのレガシーエンコーディングを継続使用している方々に影響は出ます。
その場合は、pbibtex-base を旧版に戻すか、入力エンコーディングを UTF-8 にする対応をお願いします。

ここは閉じます。

**Comment by aminophen** [comment]
ありがとうございます。

一点だけ：TL2023 pretest は既に始まっていますが，TL2022 final（文字コード判定機能未実装）はまだ閉じていないので，CTAN への投稿メッセージあるいは Karl さんに「trunk には入れていいが branch2022.final には入れないように」と伝える必要があると思います。

* https://tug.org/pipermail/tex-live/2023-February/048856.html

**Comment by t-tk** [comment]
ご指摘ありがとうございます。↓これですね。
```
Normal package updates sent to CTAN will be installed in both the
pretest and the regular (tlnet) repository for a while. 
```

こういう注意が必要とは知りませんでした。
Karlさんに伝えます。

**Comment by aminophen** [comment]
それから https://github.com/texjporg/jsclasses/issues/49#issuecomment-327079141 で触れられている

> 変換後のUTF-8に以下の文字が入ってはいけない。（JISなやつとUTF-8なやつで意味が違ってしまう。）
> U+2014, U+FF5E, U+2225, U+FF0D, U+00A2, U+00A3, U+00AC

が無いかも念のため確認しようと思います。

（nkf -w で機械変換すると発生する場合があったような記憶があるので）

**Comment by t-tk** [comment]
危険な文字を確かめてみました。

```
perl -CSD -wnle '/\x{2014}|\x{FF5E}|\x{2225}|\x{FF0D}|\x{00A2}|\x{00A3}|\x{00AC}/ and print;' *
```
で引っかかるものが無く、

```
perl -CSD -wnle '/\x{2014}|\x{FF5E}|\x{2225}|\x{FF0D}|\x{00A2}|\x{00A3}|\x{00AC}|\x{96FB}/ and print;' *
```
`で「電」(U+96FB)を含む行が引っかかりました。
危ない文字は無いと思います。

**Comment by aminophen** [comment]
> 危険な文字を確かめてみました。

早速ありがとうございます。
